import type { GitHubUser } from "./github-api"

export const sampleUsersByCountry: Record<string, GitHubUser[]> = {
  "United States": [
    {
      login: "torvalds",
      id: 1024025,
      avatar_url: "https://avatars.githubusercontent.com/u/1024025",
      html_url: "https://github.com/torvalds",
      name: "Linus Torvalds",
      company: "Linux Foundation",
      blog: "",
      location: "Portland, OR",
      bio: "Creator of Linux",
      twitter_username: null,
      public_repos: 7,
      public_gists: 0,
      followers: 210000,
      following: 0,
      created_at: "2011-09-03T15:26:22Z",
      public_contributions: 12500,
      total_contributions: 45000,
    },
    {
      login: "gaearon",
      id: 810438,
      avatar_url: "https://avatars.githubusercontent.com/u/810438",
      html_url: "https://github.com/gaearon",
      name: "Dan Abramov",
      company: "Bluesky",
      blog: "https://overreacted.io",
      location: "London, UK",
      bio: "Working on React",
      twitter_username: "dan_abramov",
      public_repos: 262,
      public_gists: 87,
      followers: 85000,
      following: 172,
      created_at: "2011-05-25T18:18:31Z",
      public_contributions: 8900,
      total_contributions: 32000,
    },
    {
      login: "sindresorhus",
      id: 170270,
      avatar_url: "https://avatars.githubusercontent.com/u/170270",
      html_url: "https://github.com/sindresorhus",
      name: "Sindre Sorhus",
      company: null,
      blog: "https://sindresorhus.com",
      location: "Thailand",
      bio: "Full-Time Open-Sourcerer",
      twitter_username: "sindresorhus",
      public_repos: 1100,
      public_gists: 56,
      followers: 53000,
      following: 50,
      created_at: "2010-12-21T18:42:05Z",
      public_contributions: 7800,
      total_contributions: 28000,
    },
    {
      login: "tj",
      id: 25254,
      avatar_url: "https://avatars.githubusercontent.com/u/25254",
      html_url: "https://github.com/tj",
      name: "TJ Holowaychuk",
      company: "Apex",
      blog: "https://apex.sh",
      location: "Victoria, BC, Canada",
      bio: null,
      twitter_username: "tjholowaychuk",
      public_repos: 298,
      public_gists: 124,
      followers: 38000,
      following: 7,
      created_at: "2008-09-18T00:11:42Z",
      public_contributions: 6500,
      total_contributions: 25000,
    },
    {
      login: "addyosmani",
      id: 110953,
      avatar_url: "https://avatars.githubusercontent.com/u/110953",
      html_url: "https://github.com/addyosmani",
      name: "Addy Osmani",
      company: "@AdobeResearch",
      blog: "https://addyosmani.com",
      location: "California",
      bio: "Engineering Manager at Google working on Chrome",
      twitter_username: "addyosmani",
      public_repos: 311,
      public_gists: 154,
      followers: 41000,
      following: 249,
      created_at: "2009-08-04T05:04:26Z",
      public_contributions: 4200,
      total_contributions: 18000,
    },
    {
      login: "yyx990803",
      id: 499550,
      avatar_url: "https://avatars.githubusercontent.com/u/499550",
      html_url: "https://github.com/yyx990803",
      name: "Evan You",
      company: null,
      blog: "https://evanyou.me",
      location: "New Jersey",
      bio: "Creator of @vuejs, @vitejs and more",
      twitter_username: "youyuxi",
      public_repos: 152,
      public_gists: 52,
      followers: 88000,
      following: 169,
      created_at: "2011-11-28T04:01:04Z",
      public_contributions: 5600,
      total_contributions: 22000,
    },
  ],
  India: [
    {
      login: "nickytonline",
      id: 833231,
      avatar_url: "https://avatars.githubusercontent.com/u/833231",
      html_url: "https://github.com/nickytonline",
      name: "Nick Taylor",
      company: "@forem",
      blog: "https://iamdeveloper.com",
      location: "Montreal, Canada",
      bio: "Senior Software Engineer",
      twitter_username: "nickytonline",
      public_repos: 244,
      public_gists: 82,
      followers: 6500,
      following: 1200,
      created_at: "2011-06-11T19:59:19Z",
      public_contributions: 3200,
      total_contributions: 12000,
    },
    {
      login: "piyushgarg-dev",
      id: 42694653,
      avatar_url: "https://avatars.githubusercontent.com/u/42694653",
      html_url: "https://github.com/piyushgarg-dev",
      name: "Piyush Garg",
      company: null,
      blog: "https://piyushgarg.dev",
      location: "India",
      bio: "Software Engineer & YouTuber",
      twitter_username: "paboruwa",
      public_repos: 124,
      public_gists: 12,
      followers: 18000,
      following: 45,
      created_at: "2018-08-26T15:59:13Z",
      public_contributions: 4800,
      total_contributions: 16000,
    },
    {
      login: "iamshadmirza",
      id: 26525269,
      avatar_url: "https://avatars.githubusercontent.com/u/26525269",
      html_url: "https://github.com/iamshadmirza",
      name: "Shad Mirza",
      company: "Deliveryhero",
      blog: "https://iamshadmirza.com",
      location: "Berlin",
      bio: "Software Engineer",
      twitter_username: "iamshadmirza",
      public_repos: 98,
      public_gists: 21,
      followers: 4200,
      following: 180,
      created_at: "2017-03-18T09:15:41Z",
      public_contributions: 2900,
      total_contributions: 11000,
    },
    {
      login: "tannerlinsley",
      id: 5580297,
      avatar_url: "https://avatars.githubusercontent.com/u/5580297",
      html_url: "https://github.com/tannerlinsley",
      name: "Tanner Linsley",
      company: "TanStack",
      blog: "https://tanstack.com",
      location: "Utah",
      bio: "Building open source since 2014",
      twitter_username: "tanaborumba",
      public_repos: 152,
      public_gists: 34,
      followers: 12000,
      following: 89,
      created_at: "2013-10-02T17:21:05Z",
      public_contributions: 5100,
      total_contributions: 19000,
    },
  ],
  Germany: [
    {
      login: "timdorr",
      id: 5377,
      avatar_url: "https://avatars.githubusercontent.com/u/5377",
      html_url: "https://github.com/timdorr",
      name: "Tim Dorr",
      company: null,
      blog: "https://timdorr.com",
      location: "Atlanta, GA",
      bio: null,
      twitter_username: "timdorr",
      public_repos: 312,
      public_gists: 89,
      followers: 4500,
      following: 124,
      created_at: "2008-04-05T22:24:15Z",
      public_contributions: 2800,
      total_contributions: 10500,
    },
    {
      login: "niklas-e",
      id: 14177356,
      avatar_url: "https://avatars.githubusercontent.com/u/14177356",
      html_url: "https://github.com/niklas-e",
      name: "Niklas",
      company: null,
      blog: "",
      location: "Germany",
      bio: "Full-Stack Developer",
      twitter_username: null,
      public_repos: 67,
      public_gists: 12,
      followers: 850,
      following: 45,
      created_at: "2015-08-12T08:42:15Z",
      public_contributions: 1900,
      total_contributions: 7500,
    },
  ],
  "United Kingdom": [
    {
      login: "mdo",
      id: 98681,
      avatar_url: "https://avatars.githubusercontent.com/u/98681",
      html_url: "https://github.com/mdo",
      name: "Mark Otto",
      company: "@github",
      blog: "https://markdotto.com",
      location: "SF",
      bio: "Creator of @twbs/bootstrap",
      twitter_username: "mdo",
      public_repos: 38,
      public_gists: 35,
      followers: 22000,
      following: 27,
      created_at: "2009-06-26T05:02:28Z",
      public_contributions: 3400,
      total_contributions: 14000,
    },
    {
      login: "fat",
      id: 169705,
      avatar_url: "https://avatars.githubusercontent.com/u/169705",
      html_url: "https://github.com/fat",
      name: "Jacob Thornton",
      company: "Cash App",
      blog: "",
      location: "NYC",
      bio: null,
      twitter_username: "fat",
      public_repos: 78,
      public_gists: 45,
      followers: 9800,
      following: 56,
      created_at: "2010-01-01T00:03:12Z",
      public_contributions: 2100,
      total_contributions: 8500,
    },
  ],
  Japan: [
    {
      login: "matz",
      id: 30733,
      avatar_url: "https://avatars.githubusercontent.com/u/30733",
      html_url: "https://github.com/matz",
      name: "Yukihiro Matsumoto",
      company: "Ruby Association",
      blog: "",
      location: "Matsue, Japan",
      bio: "Creator of Ruby",
      twitter_username: "yukihiro_matz",
      public_repos: 12,
      public_gists: 2,
      followers: 9200,
      following: 0,
      created_at: "2008-10-21T06:03:42Z",
      public_contributions: 1800,
      total_contributions: 15000,
    },
    {
      login: "ko1",
      id: 9558,
      avatar_url: "https://avatars.githubusercontent.com/u/9558",
      html_url: "https://github.com/ko1",
      name: "Koichi Sasada",
      company: "Shopify",
      blog: "http://atdot.net/~ko1/",
      location: "Japan",
      bio: "Ruby core committer",
      twitter_username: "_ko1",
      public_repos: 45,
      public_gists: 23,
      followers: 2800,
      following: 12,
      created_at: "2008-05-08T07:15:32Z",
      public_contributions: 2400,
      total_contributions: 12000,
    },
  ],
}

// Generate sample data for any country
export function getSampleDataForCountry(countryName: string): GitHubUser[] {
  // Return specific data if available
  if (sampleUsersByCountry[countryName]) {
    return sampleUsersByCountry[countryName]
  }

  // Generate placeholder data for other countries
  const placeholderUsers: GitHubUser[] = Array.from({ length: 15 }, (_, i) => ({
    login: `developer_${countryName.toLowerCase().replace(/\s+/g, "_")}_${i + 1}`,
    id: 10000 + i,
    avatar_url: `https://api.dicebear.com/7.x/identicon/svg?seed=${countryName}${i}`,
    html_url: `https://github.com/developer${i + 1}`,
    name: `Developer ${i + 1}`,
    company: i % 3 === 0 ? "Tech Corp" : null,
    blog: "",
    location: countryName,
    bio: "Software Developer",
    twitter_username: null,
    public_repos: Math.floor(Math.random() * 100) + 10,
    public_gists: Math.floor(Math.random() * 20),
    followers: Math.floor(10000 / (i + 1)) + Math.floor(Math.random() * 500),
    following: Math.floor(Math.random() * 200),
    created_at: "2020-01-01T00:00:00Z",
    public_contributions: Math.floor(5000 / (i + 1)) + Math.floor(Math.random() * 1000),
    total_contributions: Math.floor(15000 / (i + 1)) + Math.floor(Math.random() * 3000),
  }))

  return placeholderUsers.sort((a, b) => b.followers - a.followers)
}
